FROM python:3.10

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Install Playwright browsers
RUN playwright install
RUN playwright install-deps

# Copy code
COPY whatsapp_link_reader.py ./
COPY communicators communicators
COPY extractors extractors
COPY summarizers summarizers
COPY web_page_fetchers web_page_fetchers
COPY .env ./

EXPOSE 5001
ENV PYTHONPATH=/app

CMD ["python", "whatsapp_link_reader.py"]
