# Dockerfile.node
FROM node:24-alpine

WORKDIR /app

# Copy Node files
COPY package*.json bot.mjs ./

# Install Node deps
RUN npm install

# Expose any port if needed (Baileys doesn’t require)
EXPOSE 3000

CMD ["node", "bot.mjs"]
